### ISSUE TITLE
sub_gui.py can't find configloader.animesettingsloader

### ISSUE THREAD

**Issue by dwkennedy** [dix0nym/horriblesubsXDCC#1]
Should the code be working as-is from github?  sub_gui.py can't find AnimeSettingsLoader.  I can't find that class defined anywhere in the files.  Thank you :)

frobbitz@pbx:~/horriblesubsXDCC$ python3 sub_gui.py 
unable to import gi (gtk 3). starting tk gui
Traceback (most recent call last):
  File "sub_gui.py", line 7, in <module>
    import sub_gui.tk_gui as tk_gui
  File "/home/frobbitz/horriblesubsXDCC/sub_gui/tk_gui.py", line 5, in <module>
    from configloader.animesettingsloader import AnimeSettingsLoader
ModuleNotFoundError: No module named 'configloader.animesettingsloader'; 'configloader' is not a package

**Comment by dix0nym** [comment]
I guess, I just stopped refactoring the project 2 years ago. I still had some older project files on my hdd. I fixed some files. Should work - only tested on windows.

**Comment by dwkennedy** [comment]
Flawless perfection, works on Ubuntu :+1:   Thank you!
