### ISSUE TITLE
IRC server renames special characters in requested files

### ISSUE THREAD

**Issue by dwkennedy** [dix0nym/horriblesubsXDCC#3]
When a file is requested via IRC/XDCC, the server modifies the incoming filename by replacing the single apostrophe character with an underscore.  Eg, "[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - Director's Cut - 01 [720p].mkv" becomes "[HorribleSubs] Re Zero kara Hajimeru Isekai Seikatsu - Director_s Cut - 01 [720p].mkv"

Thus, the files are put into a different directory than expected.  When the local episodes are inventoried, the directory appears empty and all the files are queued again for download.  But end up overwriting the existing files in the underscore directory.

In horriblesubs.py, get_local_episodes function: I modified the anime name passed with name.replace("'", "_") which seems to fix the problem (get_local_episodes will now look in the same directory name that the IRC downloader will put the new episodes in)

def get_local_episodes(anime_folder, name):
    """return a list of files of a anime-folder inside ANIME_FOLDER"""
    episodes = []
    #print(name) # DWK
    **name = name.replace("'","_")  #DWK  account for IRC server renaming file, look in correct folder**
    #print(name) # DWK
    path = os.path.join(anime_folder, name)
    #print(path)  #DWK
    if not os.path.isdir(path):
        os.makedirs(path)
        return episodes
    for episode in os.listdir(path):

**Comment by dix0nym** [comment]
I guess its because there seems to be a difference between the anime name received from xdccparser and the name from irclib. Using your fix for now, there could be more problems with different filenames in the future.
