### ISSUE TITLE
Web server reports different file size that is delivered by IRC

### ISSUE THREAD

**Issue by dwkennedy** [dix0nym/horriblesubsXDCC#4]
Checking the file size retrieved from the webpage vs. the local file size fails, seems like the web page has incorrect file sizes and will cause unnecessary re-downloads.  I had to expand the window to +/- 45 MB to eliminate false positives (Re Zero director's cut has many problems)

There is also some debug code commented out that calculates the difference in size reported by the web page and the local file size. Sometimes the web page is too big, sometimes too small.  it's so strange!

It's all working pretty well now, thanks for sharing your hard work.  I hope I am not bothering you with these fixes!

in lib/packagehelper.py:

def get_diff_episodes(packages, local):
    """return the difference between the folder of packages and local"""
    result = []
    packages = get_ep_size_tuple(packages)
    for package in packages:
        episode = package[0]
        size = int(package[1])
        #print('package has episode: %s size: %s' % (episode, size))  #DWK
        if episode in local:
            local_size = int(local[episode][0]["size"] / (1024 * 1024))
            **#print('local has episode. package size: %d  local_size %d  difference %d' % (size, local_size, (local_size-size))) #DWK**
            **if (size - 45) <= local_size <= (size + 45):**
                continue
            #print('package: %s' % (package))
            #print('size: %d  local_size %d' % (size, local_size))
        result.append(episode)
    return sorted(result)

**Comment by dix0nym** [comment]
No, arent bothering me. Fix in commit. the difference window of 45MB seems way too big, sadly it seems there isnt a better approach.
