### ISSUE TITLE
Occassional error and program halt when decoding received data from IRC server in irclib.py

### ISSUE THREAD

**Issue by dwkennedy** [dix0nym/horriblesubsXDCC#5]
Every few hours (downloading back catalog) I would get this sort of error:

>   File "/home/doug/horriblesubsXDCC/lib/irclib.py", line 199, in receive
>     data = self.socket.recv(2048).decode('utf-8')
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 71: invalid continuation byte

I changed the encoding type in the receive function in irclib.py to ISO-8859-1 (latin), I don't think there should be extended characters in IRC commands. ISO-8859-1 is a straight 8 bit character set and won't throw that error.  After the change the program has been running for more than 12 hours without a error.  in UTF-8 encoding, an error occurs if you receive a byte indicating the start of an extended character, then receive an invalid continuation byte after that.  If the server is sending UTF-8 this situation should never occur, unless there is an error introduced in transmission.  I'm not sure why these errors don't occur more frequently if that is the case.  Ideally there would be some sort of checksum that could be used to verify the successful transmission of the file.  If these are due to transmission errors, I would expect a lot more errors that are not causing UTF-8 decoding errors (any byte < 0x7F wouldn't cause an error, or an error that results in a valid continuation byte)
 
So, while I am confused with the source of the error at least the ISO-8859-1 decoding fixes it and the process will run overnight without stopping.

    def receive(self):
        """receive line from irc-server"""
        while True:
            if not self.active:
                break
            #data = self.socket.recv(2048).decode('utf-8')
            data = self.socket.recv(2048).decode('ISO-8859-1')  #DWK fix occassional utf-8 decoding errors
            if not data:
                continue

**Comment by dix0nym** [comment]
thanks for reporting. fixed in new commit.
